// This file is regenerated by build-config.js on Vercel.
window.__API_BASE_URL = window.__API_BASE_URL || (
    window.location.hostname === 'localhost' || window.location.hostname === '127.0.0.1'
        ? 'http://localhost:5003'
        : ''
);
window.__CLOUD_DEPLOYMENT = Boolean(window.__API_BASE_URL);
